CREATE TABLE "housing_table" (
    "SITE_ADDRE" VARCHAR(200)   NOT NULL,
    "CITY" VARCHAR(100)   NOT NULL,
    "ZIP_CODE" INT   NOT NULL,
    "ZONING" VARCHAR(50)   NOT NULL,
    "SALE_PRICE" VARCHAR(100)   NOT NULL,
    "SALE_DATE" VARCHAR(100)   NOT NULL,
    "BILLING_CLASS" INT   NOT NULL,
    "YEAR_BUILT" INT   NOT NULL,
    "UNITS" INT   NOT NULL,
    "DESIGN_STYLE" VARCHAR(50)   NOT NULL,
    CONSTRAINT "pk_housing_table" PRIMARY KEY (
        "SITE_ADDRE"
     )
);

CREATE TABLE "noise_table" (
    "TOTAL_VALU" INT   NOT NULL,
	"SITE_ADDRE" VARCHAR(200)   NOT NULL,
    "AIR_NOISE" INT   NOT NULL,
    CONSTRAINT "pk_noise_table" PRIMARY KEY (
        "SITE_ADDRE"
     )
);

CREATE TABLE "crime_table" (
    "CITY" VARCHAR(50)   NOT NULL,
    "YEAR_RANGE" VARCHAR   NOT NULL,
    "VIOLENT_CRIMES" INT   NOT NULL,
    "PROPERTY_CRIMES" INT   NOT NULL,
    "TOTAL_CRIMES" INT   NOT NULL,
    CONSTRAINT "pk_crime_table" PRIMARY KEY (
        "CITY"
     )
);